### ISSUE TITLE
Tagator with select tag

### ISSUE THREAD

**Issue by rohanpande** [FaroeMedia/tagator#3]
Hello,
Thank you for plugin, 
I am trying to implement Tagator with select tag but it is not working. Can you suggest me how to implement this plugin with select tag. 
Here is what I am doing 

<select id="tagger" multiple> 
 <option>Test1</option>
 <option>Test2</option>
 <option>Test3</option>
</select> 

$(#tagger).tagator(
            prefix: 'tagator_', // CSS class prefix
            height: 'element', // auto or element
            useDimmer: false, // dims the screen when result list is visible
            showAllOptionsOnFocus: true, // shows all options even if input box is empty
            autocomplete: ['John Smith','Jane Smith','Rohan Pande'],
            onlyAvailableTags: true
); 

Does tagator have any feature where I don't need to provide autocomplete property in javascript and according to the selection in select dropdown tags will be created. 

Please also guide how do I create associated tags like id => name pair 

Thank you.

**Comment by jogvana** [comment]
Hi and thanks for your questions.

We'll look into to it asap and get back.

Kind regards
Jógvan

**Comment by ingipingi** [comment]
Tagator doesn't work with select tags. What you are probably looking for is Selectator, which does what you looking for:
https://github.com/FaroeMedia/selectator
