### ISSUE TITLE
this.Selected is undefined.

### ISSUE THREAD

**Issue by mchampaneri** [FaroeMedia/tagator#9]
I'm getting error in this line while using it with mitrhil.js

```
line 433:
	if (this.selected) {
			$(option).addClass('active');
	}
```

On comment out this line, It works fine.

**Comment by jogvana** [comment]
Thanks for the feedback. We'll look at this asap.

**Comment by ingipingi** [comment]
As this plugin is deprecated, it will no longer be actively maintained
